name: Terraform Validate

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  terraform_validate:
    name: "Format and Validate Code"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.4

    - name: Check module definition
      run: |
        if ! grep -q 'resource "azurerm_resource_group"' main.tf; then
          echo "azurerm_resource_group resource not found in main.tf!"
          exit 1
        fi
        if ! grep -q 'resource "azurerm_storage_account"' main.tf; then
          echo "azurerm_storage_account resource not found in main.tf!"
          exit 1
        fi
        echo "Module resources are present in main.tf."

    - name: Check variables definition
      run: |
        if [ ! -f "variables.tf" ]; then
          echo "variables.tf not found in module root!"
          exit 1
        fi
        echo "variables.tf is present in module root."

    - name: Check outputs definition
      run: |
        if [ ! -f "outputs.tf" ]; then
          echo "outputs.tf not found in module root!"
          exit 1
        fi
        echo "outputs.tf is present in module root."
    
    - name: Terraform Fmt
      run: terraform fmt -check -recursive -diff
  
    - name: Terraform Init
      run: terraform init
  
    - name: Terraform Validate
      run: terraform validate
